(deftheme neobones_dark
  "generated by shipwright"
  :background-mode 'light
  :kind 'color-scheme
  :family 'zenbones)

(let ((class '((class color) (min-colors 89))))
   (custom-theme-set-faces
   'neobones_dark
;; CocSearch: {"link": "Search"}
;; NeogitNotificationError: {"link": "DiagnosticError"}
;; NeogitNotificationWarning: {"link": "DiagnosticWarn"}
;; NeogitNotificationInfo: {"link": "DiagnosticInfo"}
;; NeogitDiffContextHighlight: {"link": "CursorLine"}
;; NeogitDiffDeleteHighlight: {"link": "DiffDelete"}
;; NeogitDiffAddHighlight: {"link": "DiffAdd"}
;; NeogitHunkHeader: {"link": "LineNr"}
;; NeogitHunkHeaderHighlight: {"bg": [], "fg": [], "gui": "bold"}
;; WhichKey: {"link": "Statement"}
;; WhichKeyGroup: {"link": "Special"}
;; WhichKeySeparator: {"fg": []}
;; WhichKeyValue: {"link": "Constant"}
;; TroubleNormal: {"link": "Function"}
;; TroubleText: {"link": "Function"}
;; TroubleSource: {"link": "Constant"}
;; NvimTreeNormal: {"bg": [], "fg": []}
;; NvimTreeWinSeparator: {"fg": "bg"}
;; NvimTreeCursorLine: {"bg": []}
;; NvimTreeCursorColumn: {"link": "NvimTreeCursorLine"}
;; NvimTreeRootFolder: {"gui": "bold", "fg": []}
;; NvimTreeSymlink: {"fg": []}
;; NvimTreeGitDirty: {"link": "diffChanged"}
;; NvimTreeGitNew: {"link": "diffAdded"}
;; NvimTreeGitDeleted: {"link": "diffRemoved"}
;; NvimTreeSpecialFile: {"gui": "underline", "fg": []}
;; CmpItemAbbr: {"fg": []}
;; CmpItemAbbrDeprecated: {"fg": []}
;; CmpItemAbbrMatch: {"gui": "bold", "fg": []}
;; CmpItemAbbrMatchFuzzy: {"gui": "bold", "fg": []}
;; CmpItemKind: {"fg": []}
;; CmpItemMenu: {"fg": []}
;; NnnNormal: {"link": "NvimTreeNormal"}
;; NnnNormalNC: {"link": "NnnNormal"}
;; NnnWinSeparator: {"link": "NvimTreeWinSeparator"}
;; NnnVertSplit: {"link": "NnnWinSeparator"}
;; MasonHighlight: {"fg": []}
;; MasonHighlightBlock: {"bg": [], "fg": []}
;; MasonHighlightBlockBold: {"bg": [], "fg": [], "gui": "bold"}
;; MasonHighlightSecondary: {"fg": []}
;; MasonHighlightBlockSecondary: {"bg": [], "fg": []}
;; MasonHighlightBlockBoldSecondary: {"bg": [], "fg": [], "gui": "bold"}
;; MasonMuted: {"fg": []}
;; MasonMutedBlock: {"bg": [], "fg": []}
;; MasonMutedBlockBold: {"bg": [], "fg": [], "gui": "bold"}
;; MasonHeader: {"bg": [], "fg": [], "gui": "bold"}
;; MasonError: {"link": "Error"}
;; NoiceCmdlineIcon: {"fg": []}
;; NoiceCmdlineIconSearch: {"link": "WarningMsg"}
;; NoiceCmdlinePopupBorder: {"link": "NoiceCmdlineIcon"}
;; NoiceCmdlinePopupBorderSearch: {"link": "WarningMsg"}
;; NoiceCmdlinePopupTitle: {"link": "NoiceCmdlineIcon"}
;; NoiceCompletionItemKindDefault: {"fg": []}
;; NoiceConfirmBorder: {"link": "NoiceCmdlineIcon"}
;; FlashLabel: {"bg": [], "fg": []}
;; FlashBackdrop: {"fg": []}
;; Italic: {"gui": "italic"}
;; Normal: {"bg": [], "fg": []}
;; Cursor: {"bg": [], "fg": []}
;; Visual: {"bg": []}
;; Todo: {"gui": "bold,underline"}
;; LspReferenceText: {"link": "ColorColumn"}
;; @keyword.coroutine: {"link": "Statement"}
;; @keyword.return: {"link": "Statement"}
;; @keyword.operator: {"link": "Statement"}
;; @keyword.function: {"link": "Statement"}
;; @keyword: {"link": "Statement"}
;; @include: {"link": "PreProc"}
;; Number: {"gui": "italic", "fg": []}
;; Constant: {"gui": "italic", "fg": []}
;; Title: {"gui": "bold", "fg": []}
;; Question: {"link": "MoreMsg"}
;; Directory: {"gui": "bold"}
;; WildMenu: {"bg": [], "fg": []}
;; @constant: {"gui": "bold", "fg": []}
;; @conditional: {"link": "Statement"}
;; @comment: {"link": "Comment"}
;; @character.special: {"link": "Special"}
;; @character: {"link": "Constant"}
;; @boolean: {"link": "Number"}
;; @attribute: {"link": "PreProc"}
;; @annotation: {"link": "PreProc"}
;; DiagnosticUnderlineHint: {"gui": "undercurl", "fg": "NONE", "sp": []}
;; StatusLineNC: {"bg": [], "fg": []}
;; DiagnosticVirtualTextHint: {"bg": [], "fg": []}
;; DiagnosticUnderlineError: {"gui": "undercurl", "fg": "NONE", "sp": []}
;; CurSearch: {"link": "IncSearch"}
;; DiagnosticSignHint: {"bg": "NONE", "fg": []}
;; DiagnosticSignWarn: {"bg": "NONE", "fg": []}
;; DiagnosticSignError: {"bg": "NONE", "fg": []}
;; DiagnosticUnnecessary: {"link": "DiagnosticWarn"}
;; DiagnosticDeprecated: {"link": "DiagnosticWarn"}
;; DiagnosticHint: {"fg": []}
;; DiagnosticInfo: {"fg": []}
;; DiagnosticWarn: {"link": "WarningMsg"}
;; DiagnosticError: {"link": "Error"}
;; LspCodeLens: {"link": "LineNr"}
;; LspReferenceWrite: {"link": "ColorColumn"}
;; LspReferenceRead: {"link": "ColorColumn"}
;; PmenuSbar: {"bg": []}
;; @field: {"link": "Identifier"}
;; @float: {"link": "Number"}
;; WarningMsg: {"fg": []}
;; @function: {"link": "Function"}
;; @function.builtin: {"link": "Special"}
;; Underlined: {"gui": "underline"}
;; @function.call: {"link": "Function"}
;; Bold: {"gui": "bold"}
;; @function.macro: {"link": "PreProc"}
;; Error: {"fg": []}
;; ErrorMsg: {"link": "Error"}
;; Comment: {"gui": "italic", "fg": []}
;; Conceal: {"gui": "bold,italic", "fg": []}
;; DiffDelete: {"bg": []}
;; lCursor: {"bg": [], "fg": []}
;; TermCursor: {"link": "Cursor"}
;; TermCursorNC: {"link": "lCursor"}
;; CursorLine: {"bg": []}
;; CursorColumn: {"link": "CursorLine"}
;; ColorColumn: {"bg": []}
;; DiffAdd: {"bg": []}
;; DiffChange: {"bg": []}
;; Special: {"gui": "bold", "fg": []}
;; DiffText: {"bg": [], "fg": []}
;; SpecialComment: {"gui": "NONE", "fg": []}
;; SignColumn: {"link": "LineNr"}
;; FoldColumn: {"bg": "NONE", "fg": [], "gui": "bold"}
;; Folded: {"bg": [], "fg": []}
;; CursorLineNr: {"bg": "NONE", "fg": [], "gui": "bold"}
;; MoreMsg: {"gui": "bold", "fg": []}
;; NormalFloat: {"bg": []}
;; FloatBorder: {"bg": "NONE", "fg": []}
;; Pmenu: {"bg": []}
;; PmenuSel: {"bg": []}
;; @todo: {"link": "Todo"}
;; PmenuThumb: {"bg": []}
;; Search: {"bg": [], "fg": []}
;; IncSearch: {"bg": [], "fg": [], "gui": "bold"}
;; MatchParen: {"link": "Search"}
;; DiagnosticSignInfo: {"bg": "NONE", "fg": []}
;; SpellBad: {"gui": "undercurl", "fg": []}
;; DiagnosticVirtualTextError: {"bg": [], "fg": []}
;; DiagnosticVirtualTextWarn: {"bg": [], "fg": []}
;; DiagnosticVirtualTextInfo: {"bg": [], "fg": []}
;; SpellLocal: {"link": "SpellCap"}
;; SpellRare: {"gui": "undercurl", "fg": []}
;; DiagnosticUnderlineWarn: {"gui": "undercurl", "fg": "NONE", "sp": []}
;; DiagnosticUnderlineInfo: {"gui": "undercurl", "fg": "NONE", "sp": []}
;; TabLine: {"link": "StatusLine"}
;; TabLineFill: {"link": "StatusLineNC"}
;; TabLineSel: {"gui": "bold"}
;; VertSplit: {"bg": "NONE", "fg": []}
;; WinSeparator: {"link": "VertSplit"}
;; NonText: {"fg": []}
;; SpecialKey: {"gui": "italic", "fg": []}
;; Whitespace: {"link": "NonText"}
;; EndOfBuffer: {"link": "NonText"}
;; @constant.builtin: {"link": "Number"}
;; @constant.macro: {"link": "Number"}
;; @constructor: {"link": "Special"}
;; @debug: {"link": "Special"}
;; @define: {"link": "PreProc"}
;; @exception: {"link": "Statement"}
;; Boolean: {"link": "Number"}
;; Identifier: {"fg": []}
;; Function: {"fg": []}
;; Statement: {"gui": "bold", "fg": []}
;; PreProc: {"link": "Statement"}
;; Type: {"fg": []}
;; @label: {"link": "Statement"}
;; @method: {"link": "Function"}
;; @method.call: {"link": "Function"}
;; @namespace: {"link": "Special"}
;; @none: []
;; @number: {"link": "Number"}
;; @operator: {"link": "Statement"}
;; @parameter: {"link": "Identifier"}
;; @parameter.reference: {"link": "@parameter"}
;; @preproc: {"link": "PreProc"}
;; @property: {"link": "Identifier"}
;; @punctuation.bracket: {"link": "Delimiter"}
;; @punctuation.delimiter: {"link": "Delimiter"}
;; @punctuation.special: {"link": "Delimiter"}
;; @repeat: {"link": "Statement"}
;; @storageclass: {"link": "Type"}
;; @string: {"link": "Constant"}
;; @string.escape: {"link": "Special"}
;; @string.regex: {"link": "Constant"}
;; @string.special: {"link": "Special"}
;; @symbol: {"link": "Identifier"}
;; @tag: {"link": "Special"}
;; @tag.attribute: {"link": "@property"}
;; @tag.delimiter: {"link": "Delimiter"}
;; @text: {"link": "@none"}
;; @text.danger: {"link": "Error"}
;; @text.emphasis: {"link": "Italic"}
;; @text.environment: {"link": "PreProc"}
;; @text.environment.name: {"link": "Type"}
;; @text.literal: {"link": "Constant"}
;; @text.math: {"link": "Special"}
;; @text.note: {"link": "DiagnosticInfo"}
;; @text.reference: {"link": "Constant"}
;; @text.strike: {"gui": "strikethrough"}
;; Delimiter: {"fg": []}
;; @text.strong: {"link": "Bold"}
;; @text.title: {"link": "Title"}
;; @text.underline: {"link": "Underlined"}
;; @text.uri: {"link": "Underlined"}
;; @text.warning: {"link": "WarningMsg"}
;; LineNr: {"bg": "NONE", "fg": []}
;; @type: {"link": "Type"}
;; @type.builtin: {"link": "Type"}
;; @type.definition: {"link": "Type"}
;; @type.qualifier: {"link": "Type"}
;; @variable: {"link": "Identifier"}
;; @variable.builtin: {"link": "Number"}
;; @punctuation.special.markdown: {"link": "Special"}
;; @string.escape.markdown: {"link": "SpecialKey"}
;; @text.reference.markdown: {"gui": "underline", "fg": []}
;; @text.emphasis.markdown: {"link": "Italic"}
;; @text.title.markdown: {"link": "Statement"}
;; @text.literal.markdown: {"link": "Type"}
;; @text.uri.markdown: {"link": "SpecialComment"}
;; @lsp.type.boolean: {"link": "@boolean"}
;; @lsp.type.builtinType: {"link": "@type.builtin"}
;; @lsp.type.comment: {"link": "@comment"}
;; @lsp.type.enum: {"link": "@type"}
;; @lsp.type.enumMember: {"link": "@constant"}
;; @lsp.type.escapeSequence: {"link": "@string.escape"}
;; @lsp.type.formatSpecifier: {"link": "@punctuation.special"}
;; @lsp.type.keyword: {"link": "@keyword"}
;; @lsp.type.namespace: {"link": "@namespace"}
;; @lsp.type.number: {"link": "@number"}
;; @lsp.type.parameter: {"link": "@parameter"}
;; @lsp.type.property: {"link": "@property"}
;; @lsp.type.selfKeyword: {"link": "@variable.builtin"}
;; @lsp.type.string.rust: {"link": "@string"}
;; @lsp.type.typeAlias: {"link": "@type.definition"}
;; @lsp.type.unresolvedReference: {"gui": "undercurl", "sp": []}
;; @lsp.type.variable: {"link": "@variable"}
;; @lsp.typemod.class.defaultLibrary: {"link": "@type.builtin"}
;; @lsp.typemod.enum.defaultLibrary: {"link": "@type.builtin"}
;; @lsp.typemod.enumMember.defaultLibrary: {"link": "@constant.builtin"}
;; @lsp.typemod.method.defaultLibrary: {"link": "@function.builtin"}
;; @lsp.typemod.function.defaultLibrary: {"link": "@function.builtin"}
;; @lsp.typemod.macro.defaultLibrary: {"link": "@function.builtin"}
;; @lsp.typemod.keyword.async: {"link": "@keyword.coroutine"}
;; @lsp.typemod.operator.injected: {"link": "@operator"}
;; @lsp.typemod.string.injected: {"link": "@string"}
;; @lsp.typemod.variable.defaultLibrary: {"link": "@variable.builtin"}
;; @lsp.typemod.variable.injected: {"link": "@variable"}
;; diffAdded: {"fg": []}
;; diffRemoved: {"fg": []}
;; diffChanged: {"fg": []}
;; diffOldFile: {"gui": "italic", "fg": []}
;; diffNewFile: {"gui": "italic", "fg": []}
;; diffFile: {"gui": "bold", "fg": []}
;; diffLine: {"gui": "bold", "fg": []}
;; diffIndexLine: {"fg": []}
;; @text.diff.add: {"link": "diffAdded"}
;; @text.diff.delete: {"link": "diffRemoved"}
;; gitcommitOverflow: {"link": "WarningMsg"}
;; markdownUrl: {"link": "helpHyperTextJump"}
;; markdownCode: {"link": "Type"}
;; markdownLinkText: {"gui": "underline", "fg": []}
;; markdownLinkTextDelimiter: {"link": "Delimiter"}
;; helpHyperTextEntry: {"link": "Special"}
;; helpHyperTextJump: {"fg": []}
;; helpSpecial: {"link": "Type"}
;; helpOption: {"link": "helpHyperTextJump"}
;; GitSignsAdd: {"bg": "NONE", "fg": []}
;; GitSignsChange: {"bg": "NONE", "fg": []}
;; GitSignsDelete: {"bg": "NONE", "fg": []}
;; GitGutterAdd: {"link": "GitSignsAdd"}
;; GitGutterChange: {"link": "GitSignsChange"}
;; GitGutterDelete: {"link": "GitSignsDelete"}
;; IndentBlanklineChar: {"fg": []}
;; TelescopeSelection: {"link": "CursorLine"}
;; TelescopeSelectionCaret: {"bg": [], "fg": []}
;; TelescopeMatching: {"gui": "bold", "fg": []}
;; TelescopeBorder: {"fg": []}
;; Sneak: {"link": "Search"}
;; SneakLabel: {"link": "WildMenu"}
;; SneakLabelMask: {"bg": [], "fg": []}
;; LeapMatch: {"gui": "bold,underline,nocombine"}
;; SpellCap: {"gui": "undercurl", "fg": []}
;; LeapLabelPrimary: {"bg": [], "fg": [], "gui": "bold,nocombine"}
;; StatusLine: {"bg": [], "fg": []}
;; LeapLabelSecondary: {"bg": [], "fg": [], "gui": "bold,nocombine"}
;; LeapLabelSelected: {"link": "IncSearch"}
;; HopNextKey: {"gui": "bold,underline", "fg": []}
;; HopNextKey1: {"gui": "bold,underline", "fg": []}
;; HopNextKey2: {"fg": []}
;; HopUnmatched: {"fg": []}
;; BufferCurrent: {"link": "TabLineSel"}
;; BufferVisible: {"fg": []}
;; BufferVisibleSign: {"fg": []}
;; BufferVisibleIndex: {"fg": []}
;; CocErrorSign: {"link": "DiagnosticSignError"}
;; CocWarningSign: {"link": "DiagnosticSignWarn"}
;; CocInfoSign: {"link": "DiagnosticSignInfo"}
;; CocHintSign: {"link": "DiagnosticSignHint"}
;; CocErrorHighlight: {"link": "DiagnosticUnderlineError"}
;; CocWarningHighlight: {"link": "DiagnosticUnderlineWarn"}
;; CocInfoHighlight: {"link": "DiagnosticUnderlineInfo"}
;; CocHintHighlight: {"link": "DiagnosticUnderlineHint"}
;; CocErrorVirtualText: {"link": "DiagnosticVirtualTextError"}
;; CocWarningVitualText: {"link": "DiagnosticVirtualTextWarn"}
;; CocMenuSel: {"link": "CursorLine"}
;; CocSelectedText: {"link": "SpellBad"}
;; CocCodeLens: {"link": "LineNr"}
;; CocMarkdownLink: {"gui": "underline", "fg": []}
;; yellow: []
;; bright_magenta: []
;; blue: []
;; bright_cyan: []
;; magenta: []
;; bright_white: []
;; cyan: []
;; bright_black: []
;; white: []
;; bright_red: []
;; black: []
;; bright_green: []
;; red: []
;; bright_yellow: []
;; green: []
;; bright_blue: []
 `(error ((,class (:foreground "#DE6E7C"))))
 `(cursor ((,class (:foreground "#0F191F" :background "#CEDDD7"))))
 `(isearch ((,class (:foreground "#0F191F" :background "#BE8CB3" :bold 't))))
 `(warning ((,class (:foreground "#B77E64"))))
 `(mode-line ((,class (:foreground "#C6D5CF" :background "#20303A"))))
 `(mode-line-inactive ((,class (:foreground "#D1E0DA" :background "#18252D"))))
 `(ansi-color-bright-red ((,class (:foreground "#E8838F" :background "#E8838F"))))
 `(ansi-color-bright-blue ((,class (:foreground "#92A0E2" :background "#92A0E2"))))
 `(ansi-color-bright-green ((,class (:foreground "#A0FF85" :background "#A0FF85"))))
 `(ansi-color-bright-cyan ((,class (:foreground "#65B8C1" :background "#65B8C1"))))
 `(ansi-color-bright-magenta ((,class (:foreground "#CF86C1" :background "#CF86C1"))))
 `(ansi-color-bright-yellow ((,class (:foreground "#D68C67" :background "#D68C67"))))
 `(ansi-color-bright-white ((,class (:foreground "#98A39E" :background "#98A39E"))))
 `(ansi-color-bright-black ((,class (:foreground "#263945" :background "#263945"))))
 `(ansi-color-red ((,class (:foreground "#DE6E7C" :background "#DE6E7C"))))
 `(ansi-color-blue ((,class (:foreground "#8190D4" :background "#8190D4"))))
 `(ansi-color-green ((,class (:foreground "#90FF6B" :background "#90FF6B"))))
 `(ansi-color-cyan ((,class (:foreground "#66A5AD" :background "#66A5AD"))))
 `(ansi-color-magenta ((,class (:foreground "#B279A7" :background "#B279A7"))))
 `(ansi-color-yellow ((,class (:foreground "#B77E64" :background "#B77E64"))))
 `(ansi-color-white ((,class (:foreground "#C6D5CF" :background "#C6D5CF"))))
 `(ansi-color-black ((,class (:foreground "#0F191F" :background "#0F191F"))))
 `(evil-ex-substitute-replacement ((,class (:foreground "#8190D4" :background "#1F1F24"))))
 `(eshell-prompt ((,class (:foreground "#9AA6A1" :bold 't))))
 `(minibuffer-prompt ((,class (:foreground "#9AA6A1" :bold 't))))
 `(comint-highlight-prompt ((,class (:foreground "#9AA6A1" :bold 't))))
 `(flymake-error ((,class (:foreground "#DE6E7C" :background "#251E1E"))))
 `(flymake-warning ((,class (:foreground "#B77E64" :background "#221F1E"))))
 `(flymake-note ((,class (:foreground "#8190D4" :background "#1F1F24"))))
 `(orderless-match-face-0 ((,class (:foreground "#0F191F" :background "#BE8CB3" :bold 't))))
 `(orderless-match-face-1 ((,class (:foreground "#C6D5CF" :background "#62415B"))))
 `(orderless-match-face-2 ((,class (:foreground "#B279A7" :background "#231E22"))))
 `(orderless-match-face-3 ((,class (:foreground "#8190D4" :background "#1F1F24"))))
 `(hl-line ((,class (:background "#152128"))))
 `(line-number ((,class (:foreground "#466273" :background "NONE"))))
 `(line-number-current-line ((,class (:foreground "#C6D5CF" :background "NONE" :bold 't))))
 `(window-divider ((,class (:foreground "#C6D5CF" :background "#0F191F"))))
 `(fringe ((,class (:foreground "#C6D5CF" :background "#0F191F"))))
 `(window-divider-first-pixel ((,class (:foreground "#C6D5CF" :background "#0F191F"))))
 `(window-divider-last-pixel ((,class (:foreground "#C6D5CF" :background "#0F191F"))))
 `(region ((,class (:background "#3A3E3D"))))
 `(show-paren-mismatch ((,class (:foreground "#0F191F" :background "#DE6E7C"))))
 `(lazy-highlight ((,class (:foreground "#C6D5CF" :background "#62415B"))))
 `(font-lock-delimiter-face ((,class (:foreground "#5B7E94"))))
 `(default ((,class (:foreground "#C6D5CF" :background "#0F191F"))))
 `(font-lock-string-face ((,class (:foreground "#939E99" :italic 't))))
 `(font-lock-function-name-face ((,class (:foreground "#6E99B2"))))
 `(font-lock-function-call-face ((,class (:foreground "#C6D5CF"))))
 `(font-lock-comment-face ((,class (:foreground "#536977" :italic 't))))
 `(font-lock-builtin-face ((,class (:foreground "#9AA6A1" :bold 't))))
 `(font-lock-variable-name-face ((,class (:foreground "#A7B3AE"))))
 `(font-lock-variable-use-face ((,class (:foreground "#A7B3AE"))))
 `(font-lock-keyword-face ((,class (:foreground "#C6D5CF" :bold 't))))
 `(font-lock-type-face ((,class (:foreground "#6E99B2"))))
 `(font-lock-preprocessor-face ((,class (:foreground "#C6D5CF" :bold 't))))
 `(rainbow-delimiters-base-face ((,class (:foreground "#5B7E94"))))
 `(rainbow-delimiters-depth-1-face ((,class (:foreground "#C6D5CF" :background "#0F191F"))))
 `(rainbow-delimiters-depth-2-face ((,class (:foreground "#8190D4"))))
 `(rainbow-delimiters-depth-3-face ((,class (:foreground "#B279A7"))))
 `(rainbow-delimiters-depth-4-face ((,class (:foreground "#C6D5CF"))))
 `(rainbow-delimiters-depth-5-face ((,class (:foreground "#B77E64"))))
 `(rainbow-delimiters-depth-6-face ((,class (:foreground "#90FF6B"))))
 `(rainbow-delimiters-depth-7-face ((,class (:foreground "#98A39E"))))
 `(highlight ((,class (:background "#3A3E3D"))))
 `(magit-diff-lines-heading ((,class (:foreground "#0F191F" :background "#BE8CB3" :bold 't))))
 `(magit-diff-hunk-heading-highlight ((,class (:foreground "#C6D5CF" :background "#20303A"))))
 `(magit-diff-hunk-heading ((,class (:foreground "#D1E0DA" :background "#18252D"))))
 `(magit-diff-whitespace-warning ((,class (:background "#E8838F"))))
 `(magit-diff-base-highlight ((,class (:foreground "#8190D4" :background "#1F2645"))))
 `(magit-diff-base ((,class (:background "#1F2645"))))
 `(magit-diff-added-highlight ((,class (:foreground "#90FF6B" :background "#1C2C19"))))
 `(magit-diff-added ((,class (:background "#1C2C19"))))
 `(magit-diff-removed-highlight ((,class (:foreground "#DE6E7C" :background "#3B2023"))))
 `(magit-diff-removed ((,class (:background "#3B2023"))))
 `(magit-section-highlight ((,class (:background "#152128"))))
 `(rainbow-delimiters-base-error-face ((,class (:foreground "#DE6E7C" :background "#251E1E"))))
 `(rainbow-delimiters-depth-9-face ((,class (:foreground "#DE6E7C"))))
 `(match ((,class (:foreground "#C6D5CF" :background "#62415B"))))
 `(rainbow-delimiters-depth-8-face ((,class (:foreground "#66A5AD"))))
 `(show-paren-match ((,class (:foreground "#C6D5CF" :background "#62415B"))))
 `(font-lock-constant-face ((,class (:foreground "#939E99" :italic 't))))
))
(provide-theme 'neobones_dark)

