(deftheme zenbones_dark
  "generated by shipwright"
  :background-mode 'light
  :kind 'color-scheme



  :family 'zenbones)
  
foospec name: "@keyword.coroutine", spec value:{"link": "Statement"}
spec name: "@label", spec value:{"link": "Statement"}
spec name: "@method", spec value:{"link": "Function"}
spec name: "@method.call", spec value:{"link": "Function"}
spec name: "@namespace", spec value:{"link": "Special"}
spec name: "@none", spec value:[]
spec name: "@number", spec value:{"link": "Number"}
spec name: "@operator", spec value:{"link": "Statement"}
spec name: "@parameter", spec value:{"link": "Identifier"}
spec name: "@parameter.reference", spec value:{"link": "@parameter"}
spec name: "@preproc", spec value:{"link": "PreProc"}
spec name: "@property", spec value:{"link": "Identifier"}
spec name: "@punctuation.bracket", spec value:{"link": "Delimiter"}
spec name: "@punctuation.delimiter", spec value:{"link": "Delimiter"}
spec name: "@punctuation.special", spec value:{"link": "Delimiter"}
spec name: "@repeat", spec value:{"link": "Statement"}
spec name: "@storageclass", spec value:{"link": "Type"}
spec name: "@string", spec value:{"link": "Constant"}
spec name: "@string.escape", spec value:{"link": "Special"}
spec name: "@string.regex", spec value:{"link": "Constant"}
spec name: "@string.special", spec value:{"link": "Special"}
spec name: "@symbol", spec value:{"link": "Identifier"}
spec name: "@tag", spec value:{"link": "Special"}
spec name: "@tag.attribute", spec value:{"link": "@property"}
spec name: "@tag.delimiter", spec value:{"link": "Delimiter"}
spec name: "@text", spec value:{"link": "@none"}
spec name: "@text.danger", spec value:{"link": "Error"}
spec name: "@text.emphasis", spec value:{"link": "Italic"}
spec name: "@text.environment", spec value:{"link": "PreProc"}
spec name: "@text.environment.name", spec value:{"link": "Type"}
spec name: "@text.literal", spec value:{"link": "Constant"}
spec name: "@text.math", spec value:{"link": "Special"}
spec name: "@text.note", spec value:{"link": "DiagnosticInfo"}
spec name: "@text.reference", spec value:{"link": "Constant"}
spec name: "@text.strike", spec value:{"gui": "strikethrough"}
spec name: "@text.strong", spec value:{"link": "Bold"}
spec name: "@text.title", spec value:{"link": "Title"}
spec name: "@text.underline", spec value:{"link": "Underlined"}
spec name: "@text.uri", spec value:{"link": "Underlined"}
spec name: "@text.warning", spec value:{"link": "WarningMsg"}
spec name: "@type", spec value:{"link": "Type"}
spec name: "@type.builtin", spec value:{"link": "Type"}
spec name: "@type.definition", spec value:{"link": "Type"}
spec name: "@type.qualifier", spec value:{"link": "Type"}
spec name: "@variable", spec value:{"link": "Identifier"}
spec name: "@variable.builtin", spec value:{"link": "Number"}
spec name: "@punctuation.special.markdown", spec value:{"link": "Special"}
spec name: "@string.escape.markdown", spec value:{"link": "SpecialKey"}
spec name: "@text.reference.markdown", spec value:{"gui": "underline", "fg": []}
spec name: "@text.emphasis.markdown", spec value:{"link": "Italic"}
spec name: "@text.title.markdown", spec value:{"link": "Statement"}
spec name: "@text.literal.markdown", spec value:{"link": "Type"}
spec name: "@text.uri.markdown", spec value:{"link": "SpecialComment"}
spec name: "@lsp.type.boolean", spec value:{"link": "@boolean"}
spec name: "Italic", spec value:{"gui": "italic"}
spec name: "@lsp.type.comment", spec value:{"link": "@comment"}
spec name: "@lsp.type.enum", spec value:{"link": "@type"}
spec name: "@lsp.type.enumMember", spec value:{"link": "@constant"}
spec name: "@lsp.type.escapeSequence", spec value:{"link": "@string.escape"}
spec name: "@lsp.type.formatSpecifier", spec value:{"link": "@punctuation.special"}
spec name: "@lsp.type.keyword", spec value:{"link": "@keyword"}
spec name: "@lsp.type.namespace", spec value:{"link": "@namespace"}
spec name: "@lsp.type.number", spec value:{"link": "@number"}
spec name: "@lsp.type.parameter", spec value:{"link": "@parameter"}
spec name: "@lsp.type.property", spec value:{"link": "@property"}
spec name: "@lsp.type.selfKeyword", spec value:{"link": "@variable.builtin"}
spec name: "@lsp.type.string.rust", spec value:{"link": "@string"}
spec name: "@lsp.type.typeAlias", spec value:{"link": "@type.definition"}
spec name: "@lsp.type.unresolvedReference", spec value:{"gui": "undercurl", "sp": []}
spec name: "@lsp.type.variable", spec value:{"link": "@variable"}
spec name: "@lsp.typemod.class.defaultLibrary", spec value:{"link": "@type.builtin"}
spec name: "@lsp.typemod.enum.defaultLibrary", spec value:{"link": "@type.builtin"}
spec name: "@lsp.typemod.enumMember.defaultLibrary", spec value:{"link": "@constant.builtin"}
spec name: "@lsp.typemod.method.defaultLibrary", spec value:{"link": "@function.builtin"}
spec name: "@lsp.typemod.function.defaultLibrary", spec value:{"link": "@function.builtin"}
spec name: "@lsp.typemod.macro.defaultLibrary", spec value:{"link": "@function.builtin"}
spec name: "@lsp.typemod.keyword.async", spec value:{"link": "@keyword.coroutine"}
spec name: "@lsp.typemod.operator.injected", spec value:{"link": "@operator"}
spec name: "@lsp.typemod.string.injected", spec value:{"link": "@string"}
spec name: "@lsp.typemod.variable.defaultLibrary", spec value:{"link": "@variable.builtin"}
spec name: "@lsp.typemod.variable.injected", spec value:{"link": "@variable"}
spec name: "diffAdded", spec value:{"fg": []}
spec name: "diffRemoved", spec value:{"fg": []}
spec name: "diffChanged", spec value:{"fg": []}
spec name: "diffOldFile", spec value:{"gui": "italic", "fg": []}
spec name: "diffNewFile", spec value:{"gui": "italic", "fg": []}
spec name: "diffFile", spec value:{"gui": "bold", "fg": []}
spec name: "diffLine", spec value:{"gui": "bold", "fg": []}
spec name: "diffIndexLine", spec value:{"fg": []}
spec name: "@text.diff.add", spec value:{"link": "diffAdded"}
spec name: "@text.diff.delete", spec value:{"link": "diffRemoved"}
spec name: "gitcommitOverflow", spec value:{"link": "WarningMsg"}
spec name: "markdownUrl", spec value:{"link": "SpecialComment"}
spec name: "markdownCode", spec value:{"link": "Type"}
spec name: "markdownLinkText", spec value:{"gui": "underline", "fg": []}
spec name: "markdownLinkTextDelimiter", spec value:{"link": "Delimiter"}
spec name: "helpHyperTextEntry", spec value:{"link": "Special"}
spec name: "helpHyperTextJump", spec value:{"link": "Constant"}
spec name: "helpSpecial", spec value:{"link": "Type"}
spec name: "helpOption", spec value:{"link": "Constant"}
spec name: "GitSignsAdd", spec value:{"bg": "NONE", "fg": []}
spec name: "GitSignsChange", spec value:{"bg": "NONE", "fg": []}
spec name: "GitSignsDelete", spec value:{"bg": "NONE", "fg": []}
spec name: "GitGutterAdd", spec value:{"link": "GitSignsAdd"}
spec name: "GitGutterChange", spec value:{"link": "GitSignsChange"}
spec name: "GitGutterDelete", spec value:{"link": "GitSignsDelete"}
spec name: "IndentBlanklineChar", spec value:{"fg": []}
spec name: "TelescopeSelection", spec value:{"link": "CursorLine"}
spec name: "TelescopeSelectionCaret", spec value:{"bg": [], "fg": []}
spec name: "TelescopeMatching", spec value:{"gui": "bold", "fg": []}
spec name: "TelescopeBorder", spec value:{"fg": []}
spec name: "Sneak", spec value:{"link": "Search"}
spec name: "SneakLabel", spec value:{"link": "WildMenu"}
spec name: "SneakLabelMask", spec value:{"bg": [], "fg": []}
spec name: "LeapMatch", spec value:{"gui": "bold,underline,nocombine"}
spec name: "LeapLabelPrimary", spec value:{"gui": "bold,nocombine", "fg": [], "bg": []}
spec name: "LeapLabelSecondary", spec value:{"gui": "bold,nocombine", "fg": [], "bg": []}
spec name: "LeapLabelSelected", spec value:{"link": "IncSearch"}
spec name: "HopNextKey", spec value:{"gui": "bold,underline", "fg": []}
spec name: "HopNextKey1", spec value:{"gui": "bold,underline", "fg": []}
spec name: "HopNextKey2", spec value:{"fg": []}
spec name: "HopUnmatched", spec value:{"fg": []}
spec name: "BufferCurrent", spec value:{"link": "TabLineSel"}
spec name: "BufferVisible", spec value:{"fg": []}
spec name: "BufferVisibleSign", spec value:{"fg": []}
spec name: "BufferVisibleIndex", spec value:{"fg": []}
spec name: "CocErrorSign", spec value:{"link": "DiagnosticSignError"}
spec name: "CocWarningSign", spec value:{"link": "DiagnosticSignWarn"}
spec name: "CocInfoSign", spec value:{"link": "DiagnosticSignInfo"}
spec name: "CocHintSign", spec value:{"link": "DiagnosticSignHint"}
spec name: "CocErrorHighlight", spec value:{"link": "DiagnosticUnderlineError"}
spec name: "CocWarningHighlight", spec value:{"link": "DiagnosticUnderlineWarn"}
spec name: "CocInfoHighlight", spec value:{"link": "DiagnosticUnderlineInfo"}
spec name: "CocHintHighlight", spec value:{"link": "DiagnosticUnderlineHint"}
spec name: "CocErrorVirtualText", spec value:{"link": "DiagnosticVirtualTextError"}
spec name: "CocWarningVitualText", spec value:{"link": "DiagnosticVirtualTextWarn"}
spec name: "CocMenuSel", spec value:{"link": "CursorLine"}
spec name: "CocSelectedText", spec value:{"link": "SpellBad"}
spec name: "CocCodeLens", spec value:{"link": "LineNr"}
spec name: "CocMarkdownLink", spec value:{"gui": "underline", "fg": []}
spec name: "CocSearch", spec value:{"link": "Search"}
spec name: "NeogitNotificationError", spec value:{"link": "DiagnosticError"}
spec name: "NeogitNotificationWarning", spec value:{"link": "DiagnosticWarn"}
spec name: "NeogitNotificationInfo", spec value:{"link": "DiagnosticInfo"}
spec name: "NeogitDiffContextHighlight", spec value:{"link": "CursorLine"}
spec name: "NeogitDiffDeleteHighlight", spec value:{"link": "DiffDelete"}
spec name: "NeogitDiffAddHighlight", spec value:{"link": "DiffAdd"}
spec name: "NeogitHunkHeader", spec value:{"link": "LineNr"}
spec name: "NeogitHunkHeaderHighlight", spec value:{"gui": "bold", "fg": [], "bg": []}
spec name: "WhichKey", spec value:{"link": "Statement"}
spec name: "@todo", spec value:{"link": "Todo"}
spec name: "WhichKeySeparator", spec value:{"fg": []}
spec name: "WhichKeyValue", spec value:{"link": "Constant"}
spec name: "TroubleNormal", spec value:{"link": "Function"}
spec name: "TroubleText", spec value:{"link": "Function"}
spec name: "TroubleSource", spec value:{"link": "Constant"}
spec name: "NvimTreeNormal", spec value:{"bg": [], "fg": []}
spec name: "NvimTreeWinSeparator", spec value:{"fg": "bg"}
spec name: "NvimTreeCursorLine", spec value:{"bg": []}
spec name: "NvimTreeCursorColumn", spec value:{"link": "NvimTreeCursorLine"}
spec name: "NvimTreeRootFolder", spec value:{"gui": "bold", "fg": []}
spec name: "NvimTreeSymlink", spec value:{"fg": []}
spec name: "NvimTreeGitDirty", spec value:{"link": "diffChanged"}
spec name: "NvimTreeGitNew", spec value:{"link": "diffAdded"}
spec name: "NvimTreeGitDeleted", spec value:{"link": "diffRemoved"}
spec name: "NvimTreeSpecialFile", spec value:{"gui": "underline", "fg": []}
spec name: "CmpItemAbbr", spec value:{"fg": []}
spec name: "CmpItemAbbrDeprecated", spec value:{"fg": []}
spec name: "CmpItemAbbrMatch", spec value:{"gui": "bold", "fg": []}
spec name: "CmpItemAbbrMatchFuzzy", spec value:{"gui": "bold", "fg": []}
spec name: "CmpItemKind", spec value:{"fg": []}
spec name: "CmpItemMenu", spec value:{"fg": []}
spec name: "NnnNormal", spec value:{"link": "NvimTreeNormal"}
spec name: "NnnNormalNC", spec value:{"link": "NnnNormal"}
spec name: "NnnWinSeparator", spec value:{"link": "NvimTreeWinSeparator"}
spec name: "NnnVertSplit", spec value:{"link": "NnnWinSeparator"}
spec name: "MasonHighlight", spec value:{"fg": []}
spec name: "MasonHighlightBlock", spec value:{"bg": [], "fg": []}
spec name: "MasonHighlightBlockBold", spec value:{"gui": "bold", "fg": [], "bg": []}
spec name: "MasonHighlightSecondary", spec value:{"fg": []}
spec name: "MasonHighlightBlockSecondary", spec value:{"bg": [], "fg": []}
spec name: "MasonHighlightBlockBoldSecondary", spec value:{"gui": "bold", "fg": [], "bg": []}
spec name: "MasonMuted", spec value:{"fg": []}
spec name: "MasonMutedBlock", spec value:{"bg": [], "fg": []}
spec name: "MasonMutedBlockBold", spec value:{"gui": "bold", "fg": [], "bg": []}
spec name: "MasonHeader", spec value:{"gui": "bold", "fg": [], "bg": []}
spec name: "Cursor", spec value:{"bg": [], "fg": []}
spec name: "NoiceCmdlineIcon", spec value:{"fg": []}
spec name: "NoiceCmdlineIconSearch", spec value:{"link": "WarningMsg"}
spec name: "Visual", spec value:{"bg": []}
spec name: "NoiceCmdlinePopupBorderSearch", spec value:{"link": "WarningMsg"}
spec name: "NoiceCmdlinePopupTitle", spec value:{"link": "NoiceCmdlineIcon"}
spec name: "NoiceCompletionItemKindDefault", spec value:{"fg": []}
spec name: "NoiceConfirmBorder", spec value:{"link": "NoiceCmdlineIcon"}
spec name: "FlashLabel", spec value:{"bg": [], "fg": []}
spec name: "FlashBackdrop", spec value:{"fg": []}
spec name: "WarningMsg", spec value:{"fg": []}
spec name: "Underlined", spec value:{"gui": "underline"}
spec name: "Bold", spec value:{"gui": "bold"}
spec name: "Error", spec value:{"fg": []}
spec name: "ErrorMsg", spec value:{"link": "Error"}
spec name: "Comment", spec value:{"gui": "italic", "fg": []}
spec name: "Conceal", spec value:{"gui": "bold,italic", "fg": []}
spec name: "lCursor", spec value:{"bg": [], "fg": []}
spec name: "TermCursor", spec value:{"link": "Cursor"}
spec name: "TermCursorNC", spec value:{"link": "lCursor"}
spec name: "CursorLine", spec value:{"bg": []}
spec name: "CursorColumn", spec value:{"link": "CursorLine"}
spec name: "ColorColumn", spec value:{"bg": []}
spec name: "DiffAdd", spec value:{"bg": []}
spec name: "DiffChange", spec value:{"bg": []}
spec name: "DiffDelete", spec value:{"bg": []}
spec name: "DiffText", spec value:{"bg": [], "fg": []}
spec name: "LineNr", spec value:{"bg": "NONE", "fg": []}
spec name: "SignColumn", spec value:{"link": "LineNr"}
spec name: "FoldColumn", spec value:{"gui": "bold", "fg": [], "bg": "NONE"}
spec name: "Folded", spec value:{"bg": [], "fg": []}
spec name: "CursorLineNr", spec value:{"gui": "bold", "fg": [], "bg": "NONE"}
spec name: "MoreMsg", spec value:{"gui": "bold", "fg": []}
spec name: "NormalFloat", spec value:{"bg": []}
spec name: "FloatBorder", spec value:{"bg": "NONE", "fg": []}
spec name: "Pmenu", spec value:{"bg": []}
spec name: "PmenuSel", spec value:{"bg": []}
spec name: "PmenuSbar", spec value:{"bg": []}
spec name: "PmenuThumb", spec value:{"bg": []}
spec name: "Search", spec value:{"bg": [], "fg": []}
spec name: "IncSearch", spec value:{"gui": "bold", "fg": [], "bg": []}
spec name: "MatchParen", spec value:{"link": "Search"}
spec name: "CurSearch", spec value:{"link": "IncSearch"}
spec name: "SpellBad", spec value:{"gui": "undercurl", "fg": []}
spec name: "SpellCap", spec value:{"gui": "undercurl", "fg": []}
spec name: "SpellLocal", spec value:{"link": "SpellCap"}
spec name: "SpellRare", spec value:{"gui": "undercurl", "fg": []}
spec name: "StatusLine", spec value:{"bg": [], "fg": []}
spec name: "StatusLineNC", spec value:{"bg": [], "fg": []}
spec name: "TabLine", spec value:{"link": "StatusLine"}
spec name: "TabLineFill", spec value:{"link": "StatusLineNC"}
spec name: "TabLineSel", spec value:{"gui": "bold"}
spec name: "VertSplit", spec value:{"bg": "NONE", "fg": []}
spec name: "WinSeparator", spec value:{"link": "VertSplit"}
spec name: "NonText", spec value:{"fg": []}
spec name: "SpecialKey", spec value:{"gui": "italic", "fg": []}
spec name: "Whitespace", spec value:{"link": "NonText"}
spec name: "EndOfBuffer", spec value:{"link": "NonText"}
spec name: "WildMenu", spec value:{"bg": [], "fg": []}
spec name: "Directory", spec value:{"gui": "bold"}
spec name: "Question", spec value:{"link": "MoreMsg"}
spec name: "Title", spec value:{"gui": "bold", "fg": []}
spec name: "Constant", spec value:{"gui": "italic", "fg": []}
spec name: "Number", spec value:{"gui": "italic", "fg": []}
spec name: "Boolean", spec value:{"link": "Number"}
spec name: "Identifier", spec value:{"fg": []}
spec name: "Function", spec value:{"fg": []}
spec name: "Statement", spec value:{"gui": "bold", "fg": []}
spec name: "PreProc", spec value:{"link": "Statement"}
spec name: "Type", spec value:{"fg": []}
spec name: "Special", spec value:{"gui": "bold", "fg": []}
spec name: "Delimiter", spec value:{"fg": []}
spec name: "SpecialComment", spec value:{"gui": "NONE", "fg": []}
spec name: "Todo", spec value:{"gui": "bold,underline"}
spec name: "LspReferenceText", spec value:{"link": "ColorColumn"}
spec name: "LspReferenceRead", spec value:{"link": "ColorColumn"}
spec name: "LspReferenceWrite", spec value:{"link": "ColorColumn"}
spec name: "LspCodeLens", spec value:{"link": "LineNr"}
spec name: "DiagnosticError", spec value:{"link": "Error"}
spec name: "DiagnosticWarn", spec value:{"link": "WarningMsg"}
spec name: "DiagnosticInfo", spec value:{"fg": []}
spec name: "DiagnosticHint", spec value:{"fg": []}
spec name: "DiagnosticDeprecated", spec value:{"link": "DiagnosticWarn"}
spec name: "DiagnosticUnnecessary", spec value:{"link": "DiagnosticWarn"}
spec name: "DiagnosticSignError", spec value:{"bg": "NONE", "fg": []}
spec name: "DiagnosticSignWarn", spec value:{"bg": "NONE", "fg": []}
spec name: "DiagnosticSignInfo", spec value:{"bg": "NONE", "fg": []}
spec name: "DiagnosticSignHint", spec value:{"bg": "NONE", "fg": []}
spec name: "DiagnosticVirtualTextError", spec value:{"bg": [], "fg": []}
spec name: "DiagnosticVirtualTextWarn", spec value:{"bg": [], "fg": []}
spec name: "DiagnosticVirtualTextInfo", spec value:{"bg": [], "fg": []}
spec name: "DiagnosticVirtualTextHint", spec value:{"bg": [], "fg": []}
spec name: "DiagnosticUnderlineError", spec value:{"gui": "undercurl", "fg": "NONE", "sp": []}
spec name: "DiagnosticUnderlineWarn", spec value:{"gui": "undercurl", "fg": "NONE", "sp": []}
spec name: "DiagnosticUnderlineInfo", spec value:{"gui": "undercurl", "fg": "NONE", "sp": []}
spec name: "DiagnosticUnderlineHint", spec value:{"gui": "undercurl", "fg": "NONE", "sp": []}
spec name: "@annotation", spec value:{"link": "PreProc"}
spec name: "@attribute", spec value:{"link": "PreProc"}
spec name: "@boolean", spec value:{"link": "Number"}
spec name: "@character", spec value:{"link": "Constant"}
spec name: "@character.special", spec value:{"link": "Special"}
spec name: "@comment", spec value:{"link": "Comment"}
spec name: "@conditional", spec value:{"link": "Statement"}
spec name: "@constant", spec value:{"gui": "bold", "fg": []}
spec name: "@constant.builtin", spec value:{"link": "Number"}
spec name: "@constant.macro", spec value:{"link": "Number"}
spec name: "@constructor", spec value:{"link": "Special"}
spec name: "@debug", spec value:{"link": "Special"}
spec name: "@define", spec value:{"link": "PreProc"}
spec name: "@exception", spec value:{"link": "Statement"}
spec name: "@field", spec value:{"link": "Identifier"}
spec name: "@float", spec value:{"link": "Number"}
spec name: "@function", spec value:{"link": "Function"}
spec name: "@function.builtin", spec value:{"link": "Special"}
spec name: "@function.call", spec value:{"link": "Function"}
spec name: "@function.macro", spec value:{"link": "PreProc"}
spec name: "@include", spec value:{"link": "PreProc"}
spec name: "@keyword", spec value:{"link": "Statement"}
spec name: "@keyword.function", spec value:{"link": "Statement"}
spec name: "NoiceCmdlinePopupBorder", spec value:{"link": "NoiceCmdlineIcon"}
spec name: "MasonError", spec value:{"link": "Error"}
spec name: "Normal", spec value:{"bg": [], "fg": []}
spec name: "@lsp.type.builtinType", spec value:{"link": "@type.builtin"}
spec name: "WhichKeyGroup", spec value:{"link": "Special"}
spec name: "@keyword.operator", spec value:{"link": "Statement"}
spec name: "@keyword.return", spec value:{"link": "Statement"}
(provide-theme 'zenbones_dark)
